u-boot: refresh patch to work with version 2020.07
To avoid the following build issue:

ERROR: Applying '0001-stm32mp1-Disable-ADC.patch' failed:
checking file configs/stm32mp15_basic_defconfig
Hunk #1 FAILED at 26.
Hunk #2 FAILED at 64.
Hunk #3 succeeded at 108 (offset -1 lines).
2 out of 3 hunks FAILED

Fixes: 714143d0cfa52d2b5a37d52d090cba09f0dcd8db ("u-boot: bump to version 2020.07")

Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>