u-boot: bump to version 2020.07
Since commit in [1], the U-Boot version in oe-core is 2020.07.
So, let's update this version.

Fixes:

ERROR: No recipes in default available for:
  /home/bdx-iot/koncepto/nxp/meta-stm32mp1/recipes-bsp/u-boot/u-boot_2020.04.bbappend

[1] - https://github.com/openembedded/openembedded-core/commit/db6fedd77a1a468ce65f7276bb79b5f0ddf4a0b5

Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>